#!/usr/bin/env bash
set -euo pipefail

# cfssl version
CFSSL_VERSION=1.6.5

VERSION="${1:-$CFSSL_VERSION}"
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ARCH="amd64" ;;
  aarch64) ARCH="arm64" ;;
  *)       echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac
BASE_URL="https://github.com/cloudflare/cfssl/releases/download/v${VERSION}"

curl -sLo /usr/local/bin/cfssl "${BASE_URL}/cfssl_${VERSION}_linux_${ARCH}"
curl -sLo /usr/local/bin/cfssljson "${BASE_URL}/cfssljson_${VERSION}_linux_${ARCH}"
chmod +x /usr/local/bin/cfssl /usr/local/bin/cfssljson
