#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

PODMAN=${PODMAN:-"sudo podman"}
IMAGE=${IMAGE:-"kubernix:latest"}

$PODMAN build -t "$IMAGE" .
$PODMAN run \
    --privileged \
    -v /lib/modules \
    -v /dev/mapper \
    -it "$IMAGE"
