version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.88
  - dependency-name: serde
    versions:
    - 1.0.124
  - dependency-name: syn
    versions:
    - 1.0.63
    - 1.0.66
  - dependency-name: indexmap
    versions:
    - 1.6.2
  - dependency-name: regex-syntax
    versions:
    - 0.6.23
  - dependency-name: regex
    versions:
    - 1.4.4
  - dependency-name: serde_json
    versions:
    - 1.0.64
  - dependency-name: signal-hook
    versions:
    - 0.3.5
    - 0.3.6
    - 0.3.7
  - dependency-name: crossbeam-utils
    versions:
    - 0.8.2
    - 0.8.3
  - dependency-name: textwrap
    versions:
    - 0.13.3
    - 0.13.4
  - dependency-name: nix
    versions:
    - 0.20.0
  - dependency-name: crossbeam-epoch
    versions:
    - 0.9.2
  - dependency-name: cc
    versions:
    - 1.0.67
  - dependency-name: rand_core
    versions:
    - 0.6.2
  - dependency-name: parking_lot_core
    versions:
    - 0.8.3
  - dependency-name: quote
    versions:
    - 1.0.9
