---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "{ca}"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "{dns}"
podCIDR: "{cidr}"
runtimeRequestTimeout: "15m"
tlsCertFile: "{cert}"
tlsPrivateKeyFile: "{key}"
failSwapOn: false
featureGates:
  DevicePlugins: false
port: {port}
healthzPort: {healthzPort}
