---
name: run
on:
  - push

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
      - name: run kubernix
        run: make run
